# Generated by Django 4.1.4 on 2022-12-27 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("price", models.PositiveIntegerField(default=0)),
                ("drop_shipped", models.BooleanField(default=False)),
                ("stock", models.IntegerField(default=0)),
                ("url", models.CharField(blank=True, max_length=1024)),
                ("notes", models.TextField(blank=True)),
                ("about", models.TextField(blank=True)),
                ("metadata", models.JSONField(null=True)),
                (
                    "input",
                    models.CharField(
                        choices=[
                            ("micro", "Micro USB"),
                            ("mini", "Mini USB"),
                            ("type-c", "USB-C"),
                        ],
                        default="none",
                        max_length=128,
                    ),
                ),
                (
                    "output",
                    models.CharField(
                        choices=[("type-a", "USB-A"), ("type-c", "USB-C")],
                        default="none",
                        max_length=128,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("price", models.PositiveIntegerField(default=0)),
                ("drop_shipped", models.BooleanField(default=False)),
                ("stock", models.IntegerField(default=0)),
                ("url", models.CharField(blank=True, max_length=1024)),
                ("notes", models.TextField(blank=True)),
                ("about", models.TextField(blank=True)),
                ("metadata", models.JSONField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Keyboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("price", models.PositiveIntegerField(default=0)),
                ("drop_shipped", models.BooleanField(default=False)),
                ("stock", models.IntegerField(default=0)),
                ("url", models.CharField(blank=True, max_length=1024)),
                ("notes", models.TextField(blank=True)),
                ("about", models.TextField(blank=True)),
                ("metadata", models.JSONField(null=True)),
                (
                    "form_factor",
                    models.CharField(
                        choices=[
                            ("60", "60%"),
                            ("65", "65%"),
                            ("75", "75%"),
                            ("80", "80%"),
                            ("95", "95%"),
                            ("100", "100%"),
                            ("numpad", "numpad"),
                            ("macro", "macro"),
                            ("custom", "custom"),
                        ],
                        default="custom",
                        max_length=128,
                    ),
                ),
                ("key_count", models.PositiveIntegerField(default=0)),
                ("hot_swappable", models.BooleanField(default=False)),
                ("wireless", models.BooleanField(default=False)),
                (
                    "connector",
                    models.CharField(
                        choices=[
                            ("micro", "Micro USB"),
                            ("mini", "Mini USB"),
                            ("type-c", "USB-C"),
                        ],
                        default="none",
                        max_length=128,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Keycaps",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("price", models.PositiveIntegerField(default=0)),
                ("drop_shipped", models.BooleanField(default=False)),
                ("stock", models.IntegerField(default=0)),
                ("url", models.CharField(blank=True, max_length=1024)),
                ("notes", models.TextField(blank=True)),
                ("about", models.TextField(blank=True)),
                ("metadata", models.JSONField(null=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Switches",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("price", models.PositiveIntegerField(default=0)),
                ("drop_shipped", models.BooleanField(default=False)),
                ("stock", models.IntegerField(default=0)),
                ("url", models.CharField(blank=True, max_length=1024)),
                ("notes", models.TextField(blank=True)),
                ("about", models.TextField(blank=True)),
                ("metadata", models.JSONField(null=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
