# Generated by Django 4.1.4 on 2022-12-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_switchsetimage_keycapsetimage_keyboardimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cableimage",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="componentimage",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="keyboardimage",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="keycapsetimage",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="switchsetimage",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
