# Generated by Django 4.1.4 on 2022-12-27 18:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_cable_input_alter_cable_output"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyboard",
            name="connector",
        ),
        migrations.AddField(
            model_name="cable",
            name="length_cm",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="keyboard",
            name="default_keycaps",
            field=models.CharField(
                choices=[
                    ("abs", "ABS"),
                    ("pbt", "PBT"),
                    ("wood", "Wood"),
                    ("other", "Other"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="keyboard",
            name="default_switches",
            field=models.CharField(
                choices=[
                    ("mechanical_linear", "Linear"),
                    ("mechanical_tactile", "Tactile"),
                    ("mechanical_clicky", "Clicky"),
                    ("optical", "Optical"),
                    ("hybrid", "Hybrid"),
                    ("topre", "Topre"),
                    ("unknown", ""),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="keyboard",
            name="includes_cable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="keyboard",
            name="includes_keycaps",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="keyboard",
            name="includes_switches",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="keyboard",
            name="input",
            field=models.CharField(
                choices=[
                    ("micro", "Micro USB"),
                    ("mini", "Mini USB"),
                    ("type-c", "USB-C"),
                    ("none", ""),
                ],
                default="type-c",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="keyboard",
            name="output",
            field=models.CharField(
                choices=[("type-a", "USB-A"), ("type-c", "USB-C")],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="keyboard",
            name="wireless_mode",
            field=models.CharField(
                choices=[
                    ("bluetooth", "Bluetooth"),
                    ("2.4ghz", "2.4GHz"),
                    ("combo", "Bluetooth and 2.4GHz"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="switches",
            name="switch_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mechanical_linear", "Linear"),
                    ("mechanical_tactile", "Tactile"),
                    ("mechanical_clicky", "Clicky"),
                    ("optical", "Optical"),
                    ("hybrid", "Hybrid"),
                    ("topre", "Topre"),
                    ("unknown", ""),
                ],
                default="unknown",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="cable",
            name="input",
            field=models.CharField(
                choices=[
                    ("micro", "Micro USB"),
                    ("mini", "Mini USB"),
                    ("type-c", "USB-C"),
                    ("none", ""),
                ],
                default="micro",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="cable",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="keyboard",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="keycaps",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="switches",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
