# Generated by Django 4.1.4 on 2022-12-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_cable_price_alter_component_price_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Keycaps",
            new_name="KeycapSet",
        ),
        migrations.RenameModel(
            old_name="Switches",
            new_name="SwitchSet",
        ),
    ]
