# Generated by Django 4.1.4 on 2022-12-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_rename_keycaps_keycapset_rename_switches_switchset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cable",
            name="metadata",
            field=models.JSONField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="component",
            name="metadata",
            field=models.JSONField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="keyboard",
            name="metadata",
            field=models.JSONField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="keycapset",
            name="metadata",
            field=models.JSONField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="switchset",
            name="metadata",
            field=models.JSONField(blank=True, default="", null=True),
        ),
    ]
