# Generated by Django 4.1.4 on 2022-12-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_cable_metadata_alter_component_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cable",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="component",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="keyboard",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="keycapset",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="switchset",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
    ]
