# Generated by Django 4.1.4 on 2022-12-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_cable_metadata_alter_component_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyboard",
            name="default_switches",
            field=models.CharField(
                choices=[
                    ("mechanical_linear", "Linear"),
                    ("mechanical_tactile", "Tactile"),
                    ("mechanical_clicky", "Clicky"),
                    ("optical", "Optical"),
                    ("hybrid", "Hybrid"),
                    ("topre", "Topre"),
                    ("other", "Other"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="switchset",
            name="switch_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mechanical_linear", "Linear"),
                    ("mechanical_tactile", "Tactile"),
                    ("mechanical_clicky", "Clicky"),
                    ("optical", "Optical"),
                    ("hybrid", "Hybrid"),
                    ("topre", "Topre"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=128,
            ),
        ),
    ]
