# Generated by Django 4.1.4 on 2022-12-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_squashed_0007_alter_component_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
