# Generated by Django 4.1.4 on 2022-12-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_keyboard_default_switches_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyboard",
            name="default_keycaps",
        ),
        migrations.RemoveField(
            model_name="keyboard",
            name="default_switches",
        ),
        migrations.RemoveField(
            model_name="keyboard",
            name="includes_cable",
        ),
        migrations.RemoveField(
            model_name="keyboard",
            name="includes_keycaps",
        ),
        migrations.RemoveField(
            model_name="keyboard",
            name="includes_switches",
        ),
        migrations.RemoveField(
            model_name="keyboard",
            name="wireless",
        ),
        migrations.AddField(
            model_name="keyboard",
            name="keycaps",
            field=models.CharField(
                blank=True,
                choices=[
                    ("abs", "ABS"),
                    ("pbt", "PBT"),
                    ("wood", "Wood"),
                    ("other", "Other"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="keyboard",
            name="switches",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mechanical_linear", "Linear"),
                    ("mechanical_tactile", "Tactile"),
                    ("mechanical_clicky", "Clicky"),
                    ("optical", "Optical"),
                    ("hybrid", "Hybrid"),
                    ("topre", "Topre"),
                    ("other", "Other"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cable",
            name="input",
            field=models.CharField(
                choices=[
                    ("micro", "Micro USB"),
                    ("mini", "Mini USB"),
                    ("type-c", "USB-C"),
                ],
                default="micro",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="cable",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="component",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="keyboard",
            name="input",
            field=models.CharField(
                blank=True,
                choices=[
                    ("micro", "Micro USB"),
                    ("mini", "Mini USB"),
                    ("type-c", "USB-C"),
                ],
                default="type-c",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keyboard",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="keyboard",
            name="output",
            field=models.CharField(
                blank=True,
                choices=[("type-a", "USB-A"), ("type-c", "USB-C")],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keyboard",
            name="wireless_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bluetooth", "Bluetooth"),
                    ("2.4ghz", "2.4GHz"),
                    ("combo", "Bluetooth and 2.4GHz"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keycapset",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="switchset",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
