# Generated by Django 4.1.4 on 2022-12-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_component_hidden_tag_hidden"),
    ]

    operations = [
        migrations.RenameField(
            model_name="component",
            old_name="hidden",
            new_name="live",
        ),
    ]
